name: ci
on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: soupdiver/creg-ci:latest
      # volumes:
        # - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: |
          # go test -v ./...
          cd integration_test
          docker-compose up -d -f docker-compose.yml
          sleep 5
          docker-compose down
      # - name: Build
      #   run: |
      #     goreleaser build --snapshot --clean
      
        