name: ci
on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: soupdiver/creg-ci:latest
      # volumes:
        # - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Build
        run: |
          make image-docker
          docker tag soupdiver/creg:latest soupdiver/creg:testing
      - name: Test
        run: |
          # go test -v ./...
          cd integration_test
          docker-compose up -d
          sleep 5
          docker ps -a
          docker-compose down
      # - name: Build
      #   run: |
      #     goreleaser build --snapshot --clean
      
        