name: ci
on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: soupdiver/creg-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          make image-docker
          docker tag soupdiver/creg:latest soupdiver/creg:testing
      - name: Test
        run: |
          # go test -v ./...
          docker compose -f integration_test/docker-compose.yml up -d
          sleep 5
          docker ps -a
          docker logs integration_test-consul-1
          docker compose -f integration_test/docker-compose.yml down
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          GITHUB_TOKEN=${{ secrets.FELIX_TOKEN }} goreleaser release
      
        