name: ci
on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  CI:
    runs-on: self-hosted
    # container:
    #   image: soupdiver/creg-ci:latest
    steps:
      - run : git config --global --add safe.directory $(pwd)
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          cat Makefile
          make build
      - name: Test
        run: |
          make test
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          GITHUB_TOKEN=${{ secrets.FELIX_TOKEN }}make release # goreleaser release
      
        