name: ci
on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: self-hosted
    container:
      image: soupdiver/creg-ci:latest
    steps:
      - run : git config --global --add safe.directory $(pwd)
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          make build
      - name: Test
        run: |
          # go test -v ./...
          apk add curl

          make image-docker
          docker tag soupdiver/creg:latest soupdiver/creg:testing
          
          docker compose -f integration_test/docker-compose.yml up -d
          sleep 5
          docker ps -a
          
          curl -v localhost:8500
          
          docker logs integration_test-consul-1
          docker compose -f integration_test/docker-compose.yml down
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          GITHUB_TOKEN=${{ secrets.FELIX_TOKEN }}make release # goreleaser release
      
        