name: ci
on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: |
          go test -v ./...
      - name: Build
        run: |
          goreleaser build --snapshot --clean
      
        